---
version: "3"

networks:
  app: {}
  observability: {}

volumes:
  grafana-data: {}
  postgres-data: {}
  prometheus-data: {}
  pyroscope-data: {}

services:
  # Application services
  cook:
    build: ./services/cook
    environment:
      COOK_DB_HOST: toxiproxy
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app
      - observability
    ports:
      - 8080:8080 # application

  waiter:
    build: ./services/waiter
    environment:
      COOK_ADDR: http://toxiproxy:8080/api
    networks:
      - app
      - observability
    ports:
      - 8081:8081

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: cook
      POSTGRES_PASSWORD: c00k
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U cook -d restaurant"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Network proxy to simulate latency/jitter
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.8.0
    command: -config /toxiproxy.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app
    ports:
      - 8474:8474
    volumes:
      - ./docker/toxiproxy/toxiproxy.json:/toxiproxy.json:ro

  # Observability services
  grafana:
    image: grafana/grafana:10.3.3
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    networks:
      - observability
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/all.yml:ro
      - ./docker/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml:ro
      - ./docker/grafana/dashboards:/opt/dashboards
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.50.0
    networks:
      - observability
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  pyroscope:
    image: grafana/pyroscope:1.4.0
    networks:
      - observability
    ports:
      - 4040:4040
