---
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: "http://prometheus:9090"
    isDefault: true
    version: 1
    editable: false

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    access: proxy
    orgId: 1
    url: http://pyroscope:4040
    version: 1
    editable: false
    jsonData:
      minStep: "15s"
